---
# generic options. See ?INBOmd::report() for full list and more details.
title: Afbakening van de open ruimte voor patrijs in functie van de jachtreglementering
author: 
  - firstname: Thierry
    name: Onkelinx
    email: "thierry.onkelinx@inbo.be"
    orcid: 0000-0002-1825-0097
  - firstname: Raïsa
    name: Carmen
    email: "raisa.carmen@inbo.be"
    orcid: 0000-0003-1025-8702
style: INBO
lang: nl

reviewer: 
  - firstname: Thomas
    name: Scheppers
    email: "thomas.scheppers@inbo.be"
    orcid: 0000-0002-5098-9326
year: 2022
reportnr: 2
depotnr: D/2022/3241/023
doi: doi.org/10.21436/inbor.70809860

# report specific options. See ?INBOmd::report() for full list and more details.
shortauthor: Onkelinx, T. & Carmen, R.
corresponding: thierry.onkelinx@inbo.be
cover_photo: https://img5.vildaphoto.net/asset/l/117545.jpg
cover_description: Roepende patrijs in maïsveld. © Yves Adams

# pdf report specific options. See ?INBOmd::report() for full list and more details.
embargo: 2021-12-10

# HTML report specific options. See ?INBOmd::gitbook() for full list and more details.
github-repo: inbo/patrijs-steekproefkader

floatbarrier: section

bibliography: references.bib
link-citations: TRUE
site: bookdown::bookdown_site

output:
  INBOmd::gitbook: default
  INBOmd::report: default
  INBOmd::ebook: default
  bookdown::dontrun: default
---

# Samenvatting {-}

**Waarom een open ruimte kaart?**

Het Agentschap voor Natuur en Bos (ANB) opent de jacht op patrijs een gebied enkel indien aan meerdere voorwaarden voldaan is.
Een van deze voorwaarden is dat er voldoende patrijzen aanwezig zijn.
Hiervoor gebruikt ANB als dat er minstens 3 broedparen per 100 ha open ruimte zijn.
Daarom moet een wildbeheereenheid (WBE) die op patrijs wenst te jagen, eerst inventariseren waar er allemaal patrijzen rondlopen.
Op basis van deze waarnemingen bepaalt het Instituut voor Natuur- en Bosonderzoek (INBO) het aantal broedparen in elke WBE.
Tenslotte delen we dit aantal broedparen door de oppervlakte open ruimte om tot de dichtheid van patrijs (broedparen per 100 ha open ruimte) te komen.
Om deze oppervlakte te kennen, hebben we nood aan een kaart die bepaalt wat open ruimte is.

**Waarom een nieuwe open ruimte kaart?**

Ne de tellingen van voorjaar 2021 lieten meerdere jagers ons weten dat de gebruikte open ruimte kaart niet altijd overeenkomt met de werkelijkheid.
Sommige percelen zijn open ruimte maar bebouwd of bebost.
Waardoor de oppervlakte open ruimte overschat en de dichtheid van patrijs onderschat is.

De vorige versie van de open ruimte kaart is gebaseerd op de meest recente publicatie van de biologische waarderingskaart (BWK).
Hoewel deze versie in 2020 gepubliceerd is, wil dat niet zeggen dat alle informatie uit 2020 stamt.
In de praktijk bleek zowat driekwart ouder dan 2007.
Vandaar dat we op zoek gaan naar een betere bron.

**Een _open_ open ruimte kaart**

Na het afwegen van een aantal mogelijkheden, kozen we [OpenStreetMap](https://www.openstreetmap.org) als bronkaart.
Net zoals alle andere kandidaten, is deze kaart niet perfect.
Ze is evenwel goed genoeg om te gebruiken.
En heeft als troef dat fouten relatief eenvoudig en snel te verbeteren zijn.
Bij de start van de inventarisatie krijgen de jagers een voorlopige versie van de open ruimte kaart.
Wanneer een jager een fout in de open ruimte kaart vaststelt, kan deze de fout melden of zelf aanpassen in OpenStreetMap.
Na het berekenen van het aantal broedparen kunnen we de finale versie van de open ruimte kaart op basis van de meest recente informatie uit OpenStreetMap.

Dit is een belangrijk verschil met de overige bruikbare kaarten.
Deze beschikken niet over een mogelijkheid om ze bij te werken.
Verder zijn ze gebaseerd om informatie die minstens 1 tot 2 jaar oud is.

Voor de jagers biedt deze manier van werken hun de mogelijkheid om zelf bij te dragen aan een correcte open ruimte kaart.
Aangezien OpenStreetMap de informatie met open gebruiksvoorwaarden aanbiedt, kan iedereen genieten van een verbeterde OpenStreetMap kaart.

**Een [reproduceerbare](https://nl.wikipedia.org/wiki/Reproduceerbaarheid) open ruimte kaart**

In dit rapport beschrijven we hoe we de informatie van OpenStreetMap omzetten naar een open ruimte kaart.
De omzetting hebben we als een computerprogramma uitgewerkt.
We publiceren die computerprogramma samen met de open ruimte kaart en de gebruikte bronkaarten (OpenStreetMap en grenzen jachtgebieden).
Op die manier kan iedereen de gebruikte regels (laten) nakijken of zelf uitvoeren.

\benglish

# English abstract {-}

Insert a translation of the summary here.
\eenglish

<!-- hier komt de inhoudstafel bij pdf -->
\mainmatter

# Inleiding

Sinds 2008 is de jacht op patrijs in Vlaanderen gebonden aan een aantal voorwaarden.
De eerste voorwaarde vermeldt het voldoen aan een gemiddelde dichtheid van minstens 3 broedparen per 100 ha open ruimte.
Het Instituut voor Natuur- en Bosonderzoek (INBO) staat in voor de berekening van deze dichtheden en brengt hierover advies uit aan het Agentschap voor Natuur en Bos (ANB).

Aangezien de jachtwetgeving geen definitie geeft van de open ruimte werd, kozen we bij de invoering van deze regelgeving om te werken met de biologische waarderingskaart ([BWK](https://www.vlaanderen.be/inbo/de-biologische-waarderingskaart/bwk-belang/)).
De BWK is een gebiedsdekkende inventaris van het biologische milieu en van de bodembedekking van het volledige Vlaams Gewest.
Deze kaart wordt door het INBO opgemaakt aan de hand van een inventarisatie met behulp van vooraf gedefinieerde karteringseenheden.
De verschillende karteringseenheden werden beoordeeld als behorende tot de categorie "open ruimte" of "niet-open ruimte" voor patrijs.
Op deze manier kon een afbakening van de open ruimte bepaald worden.

Voor de berekeningen van de dichtheden van de broedparen werd steeds gewerkt met de meest recente versie van de BWK.
Ook @Onkelinx2021 gebruikte de meest recente versie van de BWK [@BWK].
De verschillende versies verwijzen echter naar de kaart als geheel, niet naar de laatste update van elk polygoon in de kaart.
Zo stelt De Saeger et al. (2020) dat in de meest actuele versie ongeveer driekwart van de oppervlakte van het niet urbaan gebied gebaseerd is op een kartering van 2007 of ouder (fig. 1‐1 in @BWK).
Het gevolg is dat de BWK voor sommige gebieden niet langer het actuele landgebruik weergeeft.
Wat op zijn beurt weer aanleiding geeft tot fouten in de kaart met open ruimte relevant voor patrijs.

In het kader van de uitrol van een standaard telprotocol voor patrijs, werd daarom beslist om een alternatieve bepaling van de open ruimte voor patrijs uit te werken.
Gezien de hoeveelheid vragen en opmerkingen over de vorige kaart, willen we de nieuwe kaart tevens transparant, open en reproduceerbaar maken.
Elke betrokkene kan hierdoor de werkwijze (laten) nakijken of zelf opnieuw (laten) uitvoeren.
Om dit te kunnen garanderen gebruiken we enkel kaartmateriaal dat als [open data](https://nl.wikipedia.org/wiki/Open_data) beschikbaar is en [vrije software](https://nl.wikipedia.org/wiki/Vrije_software_en_opensourcesoftware).
In dit rapport beschreven we welke alternatieven kaarten we in overweging genomen hebben.
Vervolgens beschrijven we op welke manier we de nieuwe open ruimte kaart uitwerken.

```{r setup, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  cache = FALSE,
  warning = TRUE,
  error = FALSE,
  message = TRUE
)
library(tidyverse)
library(leaflet)
library(deldir)
library(INBOtheme)
if (interactive()) {
  theme_set(theme_inbo(base_size = 10))
} else {
  switch(
    opts_knit$get("rmarkdown.pandoc.to"),
    html = {
      opts_chunk$set(dev = "png", dpi = 72, fig.align = "center")
      theme_set(theme_inbo(base_size = 12))
    },
    latex = {
      opts_chunk$set(dev = "cairo_pdf", dpi = 300)
      theme_set(theme_inbo(base_size = 9))
      update_geom_defaults("point", list(size = 1.5))
      update_geom_defaults("text", list(size = 2))
    },
    epub3 = {
      opts_chunk$set(dev = "png", dpi = 300)
      theme_set(theme_inbo(base_size = 12))
    }
  )
}
```
